### ISSUE TITLE
Rules being ignored

### ISSUE THREAD

**Issue by goin3d** [MoeLa/DominationsMuseumCrawler#1] opened 2021-07-06 18:53 UTC
Amazing concept!  Followed the install guide and began running.  The crafting/selling works but appears to be ignoring any rule or 'keep 3 star" option.

**Comment by MoeLa** [comment] 2021-07-08 07:55
Hey goin3d,
thanks for the feedback. I assume, that you're running DomiNations and my Crawler-App in the same language. Could you give me the name of the device you're using? I only had my OnePlus 5T and a Mi 9 SE to test the app, so there might be unexpected behaviour on e.g. tablets.

Probably, the log would give me some insight as well: https://developer.android.com/studio/command-line/logcat

**Comment by goin3d** [comment] 2021-07-08 12:33
I was testing this via bluestacks (not sure if that makes a difference or not), but will try to get the log

**Comment by svalsorim** [comment] 2021-10-01 23:56
Same issue on 2 different  tablets, Asus 3s 10 and Mi Pad 4. I'm pretty sure it worked before on asus but now it does not.

**Comment by svalsorim** [comment] 2021-10-02 00:32
Just realized something, it seems problem persists only if English is used. I switched game and app to German and it appears it works, atleast for 3 star artefacts, dont understand German so I'll report back after I check did it work

**Comment by turokss** [comment] 2021-12-08 18:10
It's a masterpiece. A very cool app. But there is a problem(( the switch does not work, saves three-star artifacts. I disable saving 3 stars, but they are still saved. Otherwise, this is the best app.

**Comment by turokss** [comment] 2021-12-08 18:16
Thank you for the cool app. The only thing it works only in German and there is no way to disable saving three-star artifacts 
I tried it on different phones.
I tried it on OnePlus 5 and OnePlus 9, I can't turn it off. If possible, please make another file where three-star artifacts will be sold.

**Comment by MoeLa** [comment] 2021-12-08 23:53
I've looked into the code and the flag is just being ignored, when it comes to check whether to keep the artifact or not.

**Comment by turokss** [comment] 2021-12-08 23:59
> I've looked into the code and the flag is just being ignored, when it comes to check whether to keep the artifact or not.

can something be done about it?

**Comment by turokss** [comment] 2021-12-09 01:01
Hi now app-debug.apk is not installed

чт, 9 дек. 2021 г

**Comment by MoeLa** [comment] 2021-12-09 01:06
Yeah, it hasn't been rebuild (and pushed to github) yet.

You can either build it by yourself or you have to wait for me having time to do it :)

This issue was accidently auto-closed by merging the linked pull request.

**Comment by turokss** [comment] 2021-12-09 01:13
> Yeah, it hasn't been rebuild (and pushed to github) yet.
> 
> You can either build it by yourself or you have to wait for me having time to do it :)
> 
> This issue was accidently auto-closed by merging the linked pull request.

I will wait for you when you have time and thank you very much

**Comment by MoeLa** [comment] 2021-12-09 01:32
> > Yeah, it hasn't been rebuild (and pushed to github) yet.
> > You can either build it by yourself or you have to wait for me having time to do it :)
> > This issue was accidently auto-closed by merging the linked pull request.
> 
> I will wait for you when you have time and thank you very much

Well, you could try now.

What has been fixed:
 - Switch 'Keep 3* artifacts' is considered, whe deciding to keep/dismiss an artifact

What has **not** been fixed:
- issue of @goin3d and @svalsorim about any rule being ignored, because I can't reproduce the issue and no further information was provided
- app only working in German, because I haven't found the time to reproduce/test that bug report

**Comment by turokss** [comment] 2021-12-09 01:40
> > > Yeah, it hasn't been rebuild (and pushed to github) yet.
> > > You can either build it by yourself or you have to wait for me having time to do it :)
> > > This issue was accidently auto-closed by merging the linked pull request.
> > 
> > 
> > I will wait for you when you have time and thank you very much
> 
> Well, you could try now.
> 
> What has been fixed:
> 
> * Switch 'Keep 3* artifacts' is considered, whe deciding to keep/dismiss an artifact
> 
> What has **not** been fixed:
> 
> * issue of @goin3d and @svalsorim about any rule being ignored, because I can't reproduce the issue and no further information was provided
> * app only working in German, because I haven't found the time to reproduce/test that bug report

Thank you very much, it works well now

**Comment by BenZin93** [comment] 2023-02-07 12:22
Hello! do you still support this project? I can’t install the application - it constantly gives an error "the package appeats to be corrupt" on both the smartphone and the emulator. what could be wrong? android or architecture?

**Comment by MoeLa** [comment] 2023-02-07 12:28
> Hello! do you still support this project? I can’t install the application - it constantly gives an error "the package appeats to be corrupt" on both the smartphone and the emulator. what could be wrong? android or architecture?

I do in general, haven't used it for a while. I gonna have a look into the .apk later this week, but I can confirm for now issues with installing it.

**Comment by BenZin93** [comment] 2023-02-07 12:32
> I do in general, haven't used it for a while. I gonna have a look into the .apk later this week, but I can confirm for now issues with installing it.

Thank you. Will wait!

**Comment by MoeLa** [comment] 2023-02-10 12:51
> > I do in general, haven't used it for a while. I gonna have a look into the .apk later this week, but I can confirm for now issues with installing it.
> 
> Thank you. Will wait!

Try this one. I've rebuild the apk and could install it successfully on my OnePlus 5 with PixelExperience. If you confirm, that it works, I'll create a new release.

[app-debug.zip](https://github.com/MoeLa/DominationsMuseumCrawler/files/10707487/app-debug.zip)

**Comment by helsko** [comment] 2023-06-06 02:24
I tested the attached build with Bluestacks 5.12.0 and English settings, it works

**Closed as completed** 2024-02-25 20:57 UTC
Labels: bug
